Make isolatedDeclaration error more precise
bloomberg/TypeScript pull request #99
Opened 2023-10-12 12:55 UTC by h-joo

Titian, where'd be the best place to add for a test for this change?

2023-10-13 10:37 UTC, dragomirtitian requested changes

2023-10-13 10:37 UTC, dragomirtitian commented on src/compiler/transformers/declarations.ts
> +        function isExprEnumMember(enumDecl: EnumDeclaration, expr: Expression): boolean {
We do support expressions in enum members so `enum E { A = 1<< 10 }` would be valid. I think you should try adapt the evaluator in [checker](https://github.dev/bloomberg/TypeScript/blob/1e141504c7c6f38927b2581b9ed3f75aec3a0213/src/compiler/checker.ts#L44691). Ideally merge it with the copied evaluator in the [DTE](https://github.dev/bloomberg/TypeScript/blob/1e141504c7c6f38927b2581b9ed3f75aec3a0213/src/compiler/transformers/declarations/evaluator.ts#L20-L21)

2023-10-19 17:14 UTC, dragomirtitian approved these changes

2023-10-19 17:14 UTC, merged

2023-10-20 07:02 UTC, h-joo commented
Oh, I actually had [another PR](https://github.com/bloomberg/TypeScript/pull/102) to solve this issue differently, as you've requested